language: node_js
sudo: false
node_js:
  - '4.2'

cache:
  directories:
    - node_modules

branches:
  except:
    - /^g3_.*$/

env:
  matrix:
    - JOB=ci-checks
  global:
    - CXX=g++-4.8  # node 4 likes the G++ v4.8 compiler
    - LOGS_DIR=/tmp/junnyria-stream/logs

# node 4 likes the G++ v4.8 compiler
# see https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  # Disable the spinner
  - npm config set spin false
  # Log HTTP requests
  - npm config set loglevel http
  - npm i

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: $HEROKU

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7367a793cffa39636fc6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false